### ISSUE TITLE
Injectable String without explicit value gets invalid String object

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#344]
With the SUT

```
public class Foo {
    String foo;
}
```

and the test class

```
public class FooTest {
    @Tested(fullyInitialized = true)
    Foo sut;

    @Injectable
    String foo;

    @Test
    public void test() {
        System.out.println(sut.foo);
    }
}
```

you get the `NullPointerException`

```
java.lang.NullPointerException
    at java.lang.String.length(String.java:611)
    at java.io.Writer.write(Writer.java:157)
    at java.io.PrintStream.write(PrintStream.java:525)
    at java.io.PrintStream.print(PrintStream.java:669)
    at java.io.PrintStream.println(PrintStream.java:806)
    at FooTest.test(FooTest.java:16)
```

because the `value` array of the `String` object is `null` which is an invalid state for the `String` object. If I look at the value of `sut.foo` with the debugger it is correctly shown as `""` and I can also evaluate in the debugger `"foo" + sut.foo` to `"foo"` and not `"foonull"`, but if anything is called on the object that needs the `value` array (most methods do), then you get `NullPointerException`s.

**Comment by rliesenfeld** [comment]
This is consistent with what JMockit normally does for any mock field/parameter: an *uninitialized* instance is created. The NPE occurs because the String class, being a special case, has none of its methods mocked.

This said, I believe an improvement can be made here, since an "@Injectable String" should always be given an explicit value, either assigned to the mock field or provided through the "value" annotation attribute. So, the idea is to throw an IllegalStateException whenever an @Injectable String is found that is missing a value.

**Comment by Vampire** [comment]
Why is this? What is wrong with the default value of `""`?

**Comment by Vampire** [comment]
Besides that, `@Injectable("") String foo;` also triggers this bug.

**Comment by rliesenfeld** [comment]
Solved by the fix for #340.

**Comment by Vampire** [comment]
Well, the error changed, but it is still not working.
Now `@Injectable String foo;` or `@Injectable("") String foo;` give you the error `java.lang.IllegalArgumentException: No injectable value available for parameter "foo" in constructor Foo$Bar#Bar(String bar)`.

The JavaDoc of `Injectable` and `Injectable.value` do not state that an empty string is not allowed, just that for primitive, wrapper and enum types the textual representation has to be convertible to the according type. But for `String` I'd expect that an empty string is also fine as value.

I'd really appreciate if the empty string would work as value, but if you don't want to change this, at least the JavaDoc should clearly state that an empty string is not valid as value but that instead `@Injectable String foo = "";` has to be used.

**Comment by Vampire** [comment]
Did you see my comment or should I open a new issue for it?

**Comment by rliesenfeld** [comment]
Could you show a failing example test? I am not seeing the "No injectable value available ..." exception in FooTest.

**Comment by Vampire** [comment]
Ah, sorry, was in one of the other examples.
With this example the `System.out.println` will print `null` while it should be injected.
If you change the SUT to the following, you will get the error message from my comment:

```java
public class Foo {
    String foo;
    @Inject
    Bar bar;

    static class Bar {
        public Bar(String bar) {
        }
    }
}
```

**Comment by rliesenfeld** [comment]
Ok, now it fails.

This exception now occurs whenever a "value" @Injectable (for String, primitive/wrapper types, enums) has no explicit value. So, the test should either specify a non-empty value using the annotation attribute (@Injectable("some value") String foo), or a non-null value assigned to the injectable field (@Injectable String foo = "").

**Comment by Vampire** [comment]
I know that. That is actually what I wrote in my comment:

>The JavaDoc of `Injectable` and `Injectable.value` do not state that an empty string is not allowed, just that for primitive, wrapper and enum types the textual representation has to be convertible to the according type. But for `String` I'd expect that an empty string is also fine as value.

>I'd really appreciate if the empty string would work as value, but if you don't want to change this, at least the JavaDoc should clearly state that an empty string is not valid as value but that instead `@Injectable String foo = "";` has to be used.

What is the sense in not allowing the empty string as value? For primitives usage it is correct and documented that this is like not set, but for Strings the empty string should be fine.

**Comment by rliesenfeld** [comment]
The empty string is allowed, as shown before: @Injectable String foo = "".

**Comment by Vampire** [comment]
Don't you understand what I say or are you pretending?

What is the sense in not allowing the empty string as value *for the annotation*? For primitives usage it is correct and documented that this is like not set, but for Strings the empty string should be fine.

**Comment by rliesenfeld** [comment]
With `@Injectable("") String s`, I get a warning from my IDE that the empty string is already the default attribute value, so it doesn't need to be explicitly given. So that's the reason to have it assigned to the field instead. Also, injecting an empty string should be the exception, not the norm; usually, it's best to inject a non-empty string, and this limitation encourages that.
